import '../models/agency.dart';
import '../models/company.dart';
import '../models/trip.dart';

class MockData {
  MockData._();

  static const List<String> cities = [
    'Ouagadougou',
    'Bobo-Dioulasso',
    'Koudougou',
    'Banfora',
    'Ouahigouya',
    'Kaya',
    'Tenkodogo',
    'Fada N\'Gourma',
    'Dédougou',
    'Gaoua',
    'Kongoussi',
    'Ziniaré',
    'Réo',
    'Houndé',
    'Léo',
  ];

  static final List<Company> companies = [
    Company(
      id: 'tsr-001',
      name: 'TSR',
      phone: '+226 25 31 00 00',
      rating: 4.5,
      totalTrips: 1200,
      description:
          'Créée en 2005, TSR (Transport Sahel Région) est l\'une des compagnies de transport les plus fiables du Burkina Faso. Elle dessert plus de 30 villes avec une flotte moderne climatisée, garantissant confort et ponctualité à chaque voyage.',
      agencies: [
        Agency(
          name: 'Gare de Ouaga-Inter',
          city: 'Ouagadougou',
          phone: '+226 25 31 01 00',
          whatsApp: '+226 70 31 01 00',
          latitude: 12.3600,
          longitude: -1.5350,
        ),
        Agency(
          name: 'Agence Wemtenga',
          city: 'Ouagadougou',
          phone: '+226 25 31 02 00',
          whatsApp: '+226 70 31 02 00',
          latitude: 12.3750,
          longitude: -1.5100,
        ),
        Agency(
          name: 'Gare Routière de Bobo',
          city: 'Bobo-Dioulasso',
          phone: '+226 20 97 01 00',
          whatsApp: '+226 70 97 01 00',
          latitude: 11.1800,
          longitude: -4.2980,
        ),
        Agency(
          name: 'Agence Centre-ville',
          city: 'Bobo-Dioulasso',
          phone: '+226 20 97 02 00',
          whatsApp: '+226 70 97 02 00',
          latitude: 11.1770,
          longitude: -4.2940,
        ),
      ],
    ),
    Company(
      id: 'rakieta-001',
      name: 'Rakiéta Transport',
      phone: '+226 25 30 00 00',
      rating: 4.2,
      totalTrips: 980,
      description:
          'Rakiéta Transport, fondée en 2010, propose des voyages inter-urbains abordables et réguliers à travers tout le Burkina Faso. Connue pour son excellent rapport qualité-prix et son service clientèle de qualité.',
      agencies: [
        Agency(
          name: 'Agence Wemtenga',
          city: 'Ouagadougou',
          phone: '+226 25 30 01 00',
          whatsApp: '+226 70 30 01 00',
          latitude: 12.3780,
          longitude: -1.5080,
        ),
        Agency(
          name: 'Gare du Nord',
          city: 'Ouagadougou',
          phone: '+226 25 30 02 00',
          whatsApp: '+226 70 30 02 00',
          latitude: 12.3900,
          longitude: -1.5220,
        ),
        Agency(
          name: 'Gare de l\'Ouest',
          city: 'Ouagadougou',
          phone: '+226 25 30 03 00',
          whatsApp: '+226 70 30 03 00',
          latitude: 12.3650,
          longitude: -1.5500,
        ),
        Agency(
          name: 'Agence Sud Sud',
          city: 'Bobo-Dioulasso',
          phone: '+226 20 97 10 00',
          whatsApp: '+226 70 97 10 00',
          latitude: 11.1720,
          longitude: -4.3020,
        ),
        Agency(
          name: 'Gare du Nord ouest',
          city: 'Bobo-Dioulasso',
          phone: '+226 20 97 11 00',
          whatsApp: '+226 70 97 11 00',
          latitude: 11.1850,
          longitude: -4.3100,
        ),
        Agency(
          name: 'Gare du centre',
          city: 'Bobo-Dioulasso',
          phone: '+226 20 97 12 00',
          whatsApp: '+226 70 97 12 00',
          latitude: 11.1780,
          longitude: -4.2960,
        ),
      ],
    ),
    Company(
      id: 'stmb-001',
      name: 'STMB',
      phone: '+226 25 33 00 00',
      rating: 4.0,
      totalTrips: 750,
      description:
          'La Société de Transport et Messagerie du Burkina (STMB) est une entreprise d\'État offrant des liaisons régulières entre les principales villes du pays. Reconnue pour sa fiabilité et ses tarifs accessibles.',
      agencies: [
        Agency(
          name: 'Terminal STMB Ouaga',
          city: 'Ouagadougou',
          phone: '+226 25 33 01 00',
          whatsApp: '+226 70 33 01 00',
          latitude: 12.3620,
          longitude: -1.5310,
        ),
        Agency(
          name: 'Agence Pissy',
          city: 'Ouagadougou',
          phone: '+226 25 33 02 00',
          whatsApp: '+226 70 33 02 00',
          latitude: 12.3520,
          longitude: -1.5600,
        ),
        Agency(
          name: 'Terminal STMB Bobo',
          city: 'Bobo-Dioulasso',
          phone: '+226 20 97 20 00',
          whatsApp: '+226 70 97 20 00',
          latitude: 11.1760,
          longitude: -4.2920,
        ),
      ],
    ),
    Company(
      id: 'tgb-001',
      name: 'TGB',
      phone: '+226 25 34 00 00',
      rating: 3.8,
      totalTrips: 500,
      description:
          'Transport Grand Burkina (TGB) propose des services de transport économiques sur les axes majeurs du Burkina Faso. Idéal pour les voyageurs à petit budget cherchant un service simple et direct.',
      agencies: [
        Agency(
          name: 'Agence TGB Ouaga',
          city: 'Ouagadougou',
          phone: '+226 25 34 01 00',
          whatsApp: '+226 70 34 01 00',
          latitude: 12.3680,
          longitude: -1.5280,
        ),
        Agency(
          name: 'Agence TGB Koudougou',
          city: 'Koudougou',
          phone: '+226 25 44 01 00',
          whatsApp: '+226 70 44 01 00',
          latitude: 12.2500,
          longitude: -2.3600,
        ),
      ],
    ),
    Company(
      id: 'confort-001',
      name: 'Confort Voyage',
      phone: '+226 25 35 00 00',
      rating: 4.6,
      totalTrips: 320,
      description:
          'Confort Voyage, créée en 2018, est la référence du voyage premium au Burkina Faso. Bus VIP entièrement climatisés, WiFi à bord, sièges inclinables et service de restauration pour une expérience de voyage inégalée.',
      agencies: [
        Agency(
          name: 'Agence VIP Ouaga-Centre',
          city: 'Ouagadougou',
          phone: '+226 25 35 01 00',
          whatsApp: '+226 70 35 01 00',
          latitude: 12.3710,
          longitude: -1.5190,
        ),
        Agency(
          name: 'Lounge Aéroport',
          city: 'Ouagadougou',
          phone: '+226 25 35 02 00',
          whatsApp: '+226 70 35 02 00',
          latitude: 12.3530,
          longitude: -1.5120,
        ),
        Agency(
          name: 'Agence VIP Bobo',
          city: 'Bobo-Dioulasso',
          phone: '+226 20 97 30 00',
          whatsApp: '+226 70 97 30 00',
          latitude: 11.1810,
          longitude: -4.3000,
        ),
      ],
    ),
  ];

  static List<Trip> getTrips({
    required String departureCity,
    required String arrivalCity,
    required DateTime date,
  }) {
    final now = DateTime(date.year, date.month, date.day);

    return [
      Trip(
        id: 'trip-001',
        company: companies[0],
        departureCity: departureCity,
        arrivalCity: arrivalCity,
        departureTime: now.add(const Duration(hours: 6)),
        arrivalTime: now.add(const Duration(hours: 10, minutes: 30)),
        price: 3500,
        availableSeats: 18,
        totalSeats: 50,
        amenities: 'Climatisé • Bagages inclus',
      ),
      Trip(
        id: 'trip-002',
        company: companies[1],
        departureCity: departureCity,
        arrivalCity: arrivalCity,
        departureTime: now.add(const Duration(hours: 7, minutes: 30)),
        arrivalTime: now.add(const Duration(hours: 12)),
        price: 3000,
        availableSeats: 32,
        totalSeats: 60,
        amenities: 'Climatisé',
      ),
      Trip(
        id: 'trip-003',
        company: companies[2],
        departureCity: departureCity,
        arrivalCity: arrivalCity,
        departureTime: now.add(const Duration(hours: 9)),
        arrivalTime: now.add(const Duration(hours: 13, minutes: 45)),
        price: 2500,
        availableSeats: 5,
        totalSeats: 50,
        amenities: 'Standard',
      ),
      Trip(
        id: 'trip-004',
        company: companies[4],
        departureCity: departureCity,
        arrivalCity: arrivalCity,
        departureTime: now.add(const Duration(hours: 12)),
        arrivalTime: now.add(const Duration(hours: 16, minutes: 30)),
        price: 5000,
        availableSeats: 12,
        totalSeats: 30,
        amenities: 'VIP • Climatisé • WiFi • Repas',
      ),
      Trip(
        id: 'trip-005',
        company: companies[3],
        departureCity: departureCity,
        arrivalCity: arrivalCity,
        departureTime: now.add(const Duration(hours: 15)),
        arrivalTime: now.add(const Duration(hours: 19, minutes: 30)),
        price: 2800,
        availableSeats: 0,
        totalSeats: 45,
        status: TripStatus.full,
        amenities: 'Standard',
      ),
      Trip(
        id: 'trip-006',
        company: companies[0],
        departureCity: departureCity,
        arrivalCity: arrivalCity,
        departureTime: now.add(const Duration(hours: 18)),
        arrivalTime: now.add(const Duration(hours: 22, minutes: 30)),
        price: 3500,
        availableSeats: 24,
        totalSeats: 50,
        amenities: 'Climatisé • Bagages inclus',
      ),
    ];
  }
}
